# Generated by Django 4.2.7 on 2024-04-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
